### ISSUE TITLE
No License specified

### ISSUE THREAD

**Issue by AnotherStranger** [jchnkl/xpp#3]
I can't find a license in this repository. Could you specify which terms apply to your code?

**Comment by jotrk** [comment]
Sorry for the long delay. There is an effort going on to relicense the code under MIT, which I fully support.

For the record: I hereby declare the code to be licensed under the terms of the MIT license.

I will add a `LICENSE` file asap!

> https://github.com/jaagr/xpp/pull/10

**Comment by AnotherStranger** [comment]
Great!
Thank you :)
